spring:
 data:
  mongodb:
   authentication-database: mongo
   port: ${mongo-port}
   host: ${mongo-host}
   username: ${mongo-username}
   password: ${mongo-password}
   database: ${mongo-database}        